### ISSUE TITLE
СРОЧНО!!!СРОЧНО!!!СРОЧНО!!!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#11]
Цены:
1) Black Friday = Цена МВидео
2) Акция -50% = Цена МВидео-10%-9%
3) Black Friday+Акция -50% = Цена МВидео-4%

А НА ЭТИ КАТЕГОРИИ (_Компактные стиральные машины, Стандартные стиральные машины, Стиральные машины с вертикальной загрузкой, Узкие стиральные машины, Накопительные водонагреватели, Сплит-системы, Сплит-системы (инвертор), Вытяжки 50 см, Вытяжки 60 см, Вытяжки 90 см, Газовые дух.шкафы, Электрические дух.шкафы, Газовые панели, Электрические, индукционные панели, Встраиваемые микров. печи, Газовые плиты 50-55 см, Газовые плиты 60 см, Электрические плиты, Компактные посудомоечные машины, Посудомоечная машина (60 см), Посудомоечные машины (45 см), **Морозильные камеры, лари**, Однодверные холодильники, Холодильники с верхней морозильной камерой, Холодильники с нижней морозильной камерой_) НУЖНО ТАК:
1) Black Friday = Цена МВидео
2) Акция -50% = Цена МВидео-12%-9%
3) Black Friday+Акция -50% = Цена МВидео

**Comment by Siyet** [comment]
сделано, на будущее пиши id'шники, категорий
