### ISSUE TITLE
ЦЕНЫ СЕЙЧАС СРОЧНО ФОРМУЛЫ!!!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#14]
Цены:
1) Акция -50% = Цена МВидео-10%-9%-количество купонов*100

А НА ЭТИ КАТЕГОРИИ (_Компактные стиральные машины, Стандартные стиральные машины, Стиральные машины с вертикальной загрузкой, Узкие стиральные машины, Накопительные водонагреватели, Сплит-системы, Сплит-системы (инвертор), Вытяжки 50 см, Вытяжки 60 см, Вытяжки 90 см, Газовые дух.шкафы, Электрические дух.шкафы, Газовые панели, Электрические, индукционные панели, Встраиваемые микров. печи, Газовые плиты 50-55 см, Газовые плиты 60 см, Электрические плиты, Компактные посудомоечные машины, Посудомоечная машина (60 см), Посудомоечные машины (45 см), **Морозильные камеры, лари**, Однодверные холодильники, Холодильники с верхней морозильной камерой, Холодильники с нижней морозильной камерой_) НУЖНО ТАК:

1) Акция -50% = Цена МВидео-10%-10%-6%
2) Акция BOSCH = Цена МВидео-10%-10%-5%

**Comment by Siyet** [comment]
сделал все кроме учета количества купонов, т. е. в первом случае формула пока что выглядит так: ## * 0.9 * 0.91 -100

**Comment by Siyet** [comment]
Запилено
