### ISSUE TITLE
СРОЧНО ДЛЯ МЕНЕДЖЕРА!!!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#15]
1) Добавить в форму заказа КИЛОМЕТРАЖ (**1км=25р**), возможность выбора **до 100 км**. Так же сделать учёт данной функции в **НАКЛАДНУЮ**, отдельным полем, следующим после доставки.

2) СЕЙЧАС: при добавлении 2-го, 3-го и более товаров к доставке прибавляется **100 рублей**.

НУЖНО СДЕЛАТЬ: при добавлении 2-го, 3-го и более товаров **любых категорий** **ДОЛЖНО ПРИБАВЛЯТЬСЯ 200 рублей,**

а при добавлении 2-го, 3-го и более товаров **ИЗ ДАННЫХ КАТЕГОРИЙ** (_Компактные стиральные машины, Стандартные стиральные машины, Стиральные машины с вертикальной загрузкой, Узкие стиральные машины, Сушильные машины, Компактные дух.шкаф, Накопительные водонагреватели, Сплит-системы, Сплит-системы (инвертор), Вытяжки 50 см, Вытяжки 60 см, Вытяжки 90 см, Газовые дух.шкафы, Электрические дух.шкафы, Газовые панели, Электрические, индукционные панели, Встраиваемые микров. печи, Газовые плиты 50-55 см, Газовые плиты 60 см, Электрические плиты, Компактные посудомоечные машины, Посудомоечная машина (60 см), Посудомоечные машины (45 см), **Морозильные камеры, лари**, Однодверные холодильники, Холодильники с верхней морозильной камерой, Холодильники с нижней морозильной камерой_) **ДОЛЖНО ПРИБАВЛЯТЬСЯ 300 рублей,**

3) ДОБАВИТЬ ГАЛОЧКИ: **ЕСТЬ лифт, НЕТ лифта** (просто галочки, пока ничего более), конечно же в форму заказа (так же обновить информацию в разделе **Доставка, оплата**...кратко опишу, а ты там напиши по русски: **Если лифт имеется и грузовой и пассажирский, то в стоимость доставки входит подъём. Если лифт только пассажирский, то нужно уточнять, точно ли пройдёт товар в проём, если да, то в стоимость доставки входит подъём, если нет, то и лифта нет получается. Если лифта нет вообще, то заказ можно оплатить и принять на первом этаже, либо платный подъём, уточняйте у менеджера.**

4) В форме заказа ПРОСТО СДЕЛАТЬ ПОЛЯ: **ФИО, почта, телефон +доп.телефон, город, улица, дом, корпус/строение, подъезд, этаж, квартира/офис, километраж, лифт: да/нет** (все эти поля, должны быть обязательными)

**Comment by Siyet** [comment]
Я добавил категориям галочку: Это категория КБТ? Проставь ее всем, а напрягает массив категорий, который ты каждый раз пишешь.

**Comment by Siyet** [comment]
пункт 2, с учетом того, что ты проставишь категориям признак принадлежности к КБТ: **ГОТОВО**

**Comment by Siyet** [comment]
пункт 3: **ГОТОВО**

**Comment by Siyet** [comment]
пункт 4, все сделано, за исключением адреса: данное поле оставил пока что целым

**Comment by Siyet** [comment]
Пункт 1 - **СДЕЛАНО**, итого сделано все, кроме разбиения адреса на отдельные поля, что будет вынесено в отдельный issue

**Comment by Siyet** [comment]
Я добавил категориям галочку: Это категория КБТ? Проставь ее всем, а напрягает массив категорий, который ты каждый раз пишешь.
