### ISSUE TITLE
Режим работы +раздел КОНТАКТЫ!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#18]
1) понедельник-пятница с 10 до 20 (_указать в разделе КОНТАКТЫ и НА ГЛАВНОЙ СТРАНИЦЕ_)

2) суббота с 11 до 18 (_указать в разделе КОНТАКТЫ и НА ГЛАВНОЙ СТРАНИЦЕ_)

3) воскресенье ВЫХОДНОЙ, но оформить заказ на сайте можно. По оформленным заказам в воскресенье, связываемся в понедельник до 11:00 (описать это как-нибудь в двух словах, по русски)

4) праздники (_**если будут выходные в праздничные дни, мы укажем на сайте, на главное странице**_).  (_указать в разделе КОНТАКТЫ_)

5) В разделе _КОНТАКТЫ_ указать:
 _ОСНОВНОЙ НОМЕР: +7(495)532-51-34_ (указать на главной странице тоже)
 _ДОП. НОМЕР: +7(495)532-51-64_ (указать на главной странице тоже)

6) Наименование: _DIELSTORE_ взять в кавычки _"DIELSTORE"_ (В РАЗДЕЛЕ КОНТАКТЫ)

**_Как всё сделаешь, скажи, я укажу на маркете тоже время работы! Это нужно будет сделать чуть ли не одновременно._**

**Comment by Siyet** [comment]
все сделаю кроме 5-го пункта

**Comment by Maksromashkin** [comment]
1) почему не сделан 5-ый пункт?
2) всё сделанно я так понимаю на новом дизайне, на старом даже и не видно, правильно?)

**Comment by Siyet** [comment]
ничего не сдедано, сделаЮ позже все, что ты написал, кроме 5го пункта в кавычки заключать название на главной странице я не буду

**Comment by Maksromashkin** [comment]
В кавычки нужно взять в РАЗДЕЛЕ КОНТАКТЫ!
