### ISSUE TITLE
КОРЗИНА - НОВЫЙ ДИЗАЙН!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#19]
1) Если в корзине есть товар, то я хотел бы видеть количество товаров в корзине **НЕ НАВОДЯ КУРСОР**.
2) Наводя курсор на корзину, если в корзине есть товар... нужно исправить инфу оранжевым цветом:
**-сейчас указано**: _Общая стоимость товаров в корзине указана без учёта доставки. Стоимость доставки уточняйте у оператора, либо в разделе "Доставка/самовывоз", либо при самостоятельном оформлении заказа итоговая сумма пересчитается автоматически._
**-НУЖНО УКАЗАТЬ**: _Общая стоимость товаров указана без учёта доставки. Стоимость доставки уточняйте у оператора, либо при самостоятельном оформлении заказа итоговая сумма пересчитается автоматически._

**_итог: с корзиной всё ок!_**

**Comment by Siyet** [comment]
Готово
