### ISSUE TITLE
СРОЧНЕЕ ВСЕХ СРОЧНЫХ!!!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#2]
На маркете у нас есть ПРАЙС, нужно сделать так, чтобы НЕКОТОРЫЕ КАТЕГОРИИ не попадали в данный прайс. Другими словами: категория и товар в ней есть у нас на сайте, но в прайсе для маркета нет. В пример можешь взять эти категории для начала: 
-Наушники
-Прочие ТВ аксессуары
-Кронштейны/стойки/подставки
-Спутниковое/цифровое ТВ
-Аксесс. для телеф./планш.
-Стёкла для телефонов.
Приём, приём! Как слышно? И как мне понимать что ты прочёл как минимум???

**Comment by Siyet** [comment]
Под своим сообщением ты увидишь, что я назначил на себя исполнение задачи, примерно вот так:
![image](https://user-images.githubusercontent.com/4410812/31905587-57ddd788-b837-11e7-9c03-eb2d1c02e20d.png)

А также в верхнем правом углу есть кнопка с глазом, кликаешь открывается меню, в нем выбираешь **Watching** и тебе на почту станут приходить уведомления.
![image](https://user-images.githubusercontent.com/4410812/31905722-cb2bcba0-b837-11e7-889c-62347bad32e0.png)

**Comment by Siyet** [comment]
Выполнено. У категорий добавлено соответствующее поле. Обращаю внимание, что действие флага **не распространяется на дочерние категории**.
