### ISSUE TITLE
ДОСТАВКА В КАРТОЧКЕ КАЖДОГО ТОВАРА!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#20]
1) Заходя в каждый товар, я хотел бы сразу видеть стоимость доставки по Москве в пределах МКАД (ПОД ОПИСАНИЕМ ТОВАРА) - исходя из стоимости, которую я указываю в категориях, с комментарием: _**Стоимость доставки по Москве (в пределах МКАД) одной единицы данного товара. Стоимость доставки более одной единицы уточняйте у оператора, либо при самостоятельном оформлении заказа итоговая сумма пересчитается автоматически. При доставке за пределы МКАД к основной стоимости доставки прибавляется 25₽/км. Если нет лифта или он не исправен, то подъём (если он требуется) оплачивается отдельно, стоимость подъёма уточняйте у оператора.**_

**Comment by Siyet** [comment]
Запилино
Текст написал такой:
Обратите, внимание, что за доставку за пределы МКАД и подъем на этаж по лестнице взимается отдельная плата, подробнее при оформлении заказа, либо в разделе Доставка и оплата
