### ISSUE TITLE
новый дизайн - раздел ОТЗЫВЫ

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#24]
1) Сделать синхронизацию отзывов с маркета (до 5 отзывов, ПОСЛЕДНИХ), обновлять ежедневно, неважно какие, хорошие или плохие, главное ежедневное обновление и последние 5 отзывов.

2) Запилить иконку отзывов (как на главной странице) и рядом с ней описать русским языком акцию CASHBACK - 200р. за отзыв, на счёт мобильного номера указанного в заказе (**_есть баннер уже на новом дизайне_**)
**Условия**:
- Указать НОМЕР ЗАКАЗА
- Какой товар заказывали
- 5 звёзд

3) **Обратная связь**: Если у клиента есть замечания или предложения по улучшению качества обслуживания, он/она может оставить комментарий заполнив 3 поля:
- ФИО
- Почта
- Комментарий (нажимает отправить и нам это приходит на почту)

**_Все 3 раздела сделать в таком порядке как я описал, только текст, как-нибудь сам напиши по русски._**

**Comment by Siyet** [comment]
2. не понял, что за иконка?

**Comment by Siyet** [comment]
Сделано все, кроме иконки во втором пункте

**Comment by Maksromashkin** [comment]
![default](https://user-images.githubusercontent.com/33026187/33896231-5f3016dc-df73-11e7-89a3-7cc51e685c58.jpg) ЭТУ ИКОНКУ БЫЛО БЫ НЕПЛОХО ЗАПИЛИТЬ И НА ГЛАВНОЙ СТРАНИЦЕ И НЕПОСРЕДСТВЕННО В САМОЙ АКЦИИ О ОТЗЫВАХ.

-ЕЩЁ, ПОСЛЕ ДАННОГО ТЕКСТА - _Оставьте свой отзыв на Яндекс.Маркете и получите cashback в размере 200₽ на номер своего мобильного телефона, указанного в заказе._ НУЖНО ДОПИСАТЬ: **Вы поможете нам стать лучше.**

**Comment by Maksromashkin** [comment]
на странице отзывов расположить всё в таком порядке:
1) АКЦИЯ CASHBACK!
Оставьте свой отзыв на Яндекс.Маркете и получите cashback в размере 200₽ на номер своего мобильного телефона, указанного в заказе. _**Вы поможете нам стать лучше!**_

Условия акции:
• обязательно укажите номер заказа
• не забудьте упомянуть какой товар Вы заказывали
• и мы ждем от Вас наивысшей оценки в в 5 звёзд

2) Отзывы, которые будут синхронизироваться.

3) Обратная связь

**Comment by Siyet** [comment]
Готово
