### ISSUE TITLE
новый дизайн - раздел АКЦИИ

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#25]
1) Сделать в админке РАЗДЕЛ АКЦИИ и чтобы я мог их добавлять вручную всегда сам.
2) При добавлении акции мне нужны поля:
- название акции (обязательное поле)
- описание акции (обязательное поле)
- фоторгафия (обязательное поле)
- ссылка (НЕ обязательно поле)
3) В самом разделе акции должны выглядеть примерно так: https://www.mvideo.ru/vse-akcii (опусти ниже и увидишь, там картинка и под ней краткое описание, но при нажатии на данную акцию, она должна открываться полностью, с описание которое я буду добавлять вручную, за исключением тех акций, на которые я буду устанавливать определённые ссылки (например акция с товаром каким-либо и при нажатии на данную акцию, будет перекидывать на страницу с товаром)

**Comment by Siyet** [comment]
Что ты хочешь писать в описании? на сайте МВидео на странице акции набор картинок друг под другом. Что хочешь ты? возможность также загрузить в админке набор картинок или тебе нужен текстовый редактор с возможностью вставки картинок?

**Comment by Siyet** [comment]
В общем пока запилино так:
Я объединил Акции с сущностью Рекламные слайды, теперь раздел в админке называется Акции.
У Акции есть галочка "На главной странице", если поставишь, то картинка акции будет отображаться на главной странице в рекламных слайдах
Период действия я пока не делал, когда-нибудь потом реализую, могу вообще убрать эти поля
Наименование акции поле обязательное, поэтому имеющимся акциям я проставил "-", описание пока просто многострочный текст, необязательный к заполнению.
Попробуй и отпишись.

**Comment by Maksromashkin** [comment]
Сань, всё правильно... всё работает, КРОМЕ:
Если я у акции **СНИМАЮ ГАЛОЧКУ _Отображать на главной?_**, то баннер в слайдах всё равно остаётся. Исправишь? как исправишь, можешь задание делать выполненным !

**Comment by Siyet** [comment]
Исправлено
