### ISSUE TITLE
Сделать ещё одно поле ЦЕНЫ в АДМИНКЕ в карточке товара

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#26]
Если у меня на товар акция и я хотел бы установить ещё и зачёркнутую цену...
Сделать поле зачёркнутой цены, чтобы если я вписываю туда цену, то у нас на сайте, в карточке товара рядом с нормальной ценой, появлялась ещё и зачёркнутая цена.
Это поле **_не должно_** зависеть ни от чего, а конкретно от обновления цен. Таким образом, я буду вручную ставить галочку _ФИКСИРОВАННАЯ ЦЕНА_ и устанавливать **_зачёркнутую цену_** и при обновлении цен, данный товар должен просто пропускаться.

**Comment by Siyet** [comment]
Готово, в новом дизайне, можешь при помощи поиска пока проверить, там товары отображаются
