### ISSUE TITLE
новый дизайн!

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#27]
- На главной странице, слева у нас указаны разделы. Если у раздела есть ещё подРазделы, то нажимая на них показываются все подРазделы, но если нажать на три-четыре таких раздела, то открытыми остаются все остальные тоже - исправить это нужно. Чтобы нажимая на другой раздел, предыдущий у тебя закрывался.
- Так же если я нажимаю на раздел, в котором есть подРазделы нужно сделать так, чтобы и иконки с разделами всеми по центру сайта менялись тоже на ту страницу, которую ты нажал в левом меню.

Надеюсь понятно описал ))))))

**Comment by Siyet** [comment]
Чувак, первое не удобно, второе бессмыслено
По первому: Если человек ищет что-либо, то удобнее когда они все открываются, каждый раз кажется, что в одном из закрытых то, что тебе нужно и ты покругу их перебираешь. К тому же если промахнулся, то ты просто кликаешь туда же чтобы скрыть развернувшийся блок, а если остальные будут сворачиваться, то пункт по которому ты кликнул будет уезжать вверх или вниз. в зависимости от того, сколько дочерних разделов в текущем и только что закрытом разделах, т.о. ты быстро понял что открыл не то, тут кликаешь еще раз, чтобы свернуть, а раздел уже уехал, в итоге ты попал в другой и пиздец вообще потерялся.
По второму: слева меню по разделам для того так и устроено, чтобы находясь, например, на странице товара, можно было посмотреть дерево категорий не уходя со страницы. А если ты хочешь скакать из категории в категорию - есть главная в которой есть квадратики с категориями, кликаешь и проваливаешься на страницу категории и видишь сразу только то, что касательно текущей категории.

Надеюсь понятно описал))) а если не понял, то забей и доверься моему опыту

**Comment by Maksromashkin** [comment]
ок, тогда это задание выполнено, нужно убирать отсюда
