### ISSUE TITLE
СРОЧНО! "Отстойник" товаров, которые кончились (база товаров)

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#4]
Итак! Попробую описать чего хочу. )
При обновлении цен на некоторых товарах снимаются галочки публикации, по различным причинам. Было бы неплохо создать раздел(каталог) товаров, в который попадали бы товары, у которых публикация снята уже после 20-го обновления цен ПОДРЯД. При этом данные товары уже находясь в этом разделе(каталоге) НЕ ДОЛЖНЫ принимать участие в обновлении цен, но иметь возможность это сделать по отдельному запросу и если товар снова в продаже, то он снова попадает с обычный раздел(каталог), которым мы пользуемся и сейчас.

**Comment by Siyet** [comment]
Предлагаю так:
Добавляем товару поле **Кол-во не успешных обновлений подряд**. 
В перечне товаров добавляю фильтр, например, **Отстойник**, в который будут попадать те товары, у которых значение данного поля `20`. Учитывать будем только автоматическое обновление. 
Принудительное обновление цен через админку, соответственно, учитывать не будем.
Если у товара обновление цены прошло успешно, то счетчик сбрасываем.
Также счетчик можно будет сбросить у конкретного товара самому.
Добавлю возможность обновлять цены по выбранным товарам.
Товары со значением `20` не будут обновляться при периодическом обновлении _(то что автоматически в пн и чт)_, но обновятся если выбрать их из списка товаров и выполнить над ними действие **Обновить цены** (которое я добавлю в перечень действий).

_P. S. кстати, я добавил возможность выбранной группе товаров, категорий или формул проставлять значение полей **Опубликовано** и **Не публиковать на Маркете** (это поле кроме товаров)._

**Comment by Siyet** [comment]
Готово, проверяй

**Comment by Maksromashkin** [comment]
а где товары которые не опубликованы?

**Comment by Siyet** [comment]
готово
