### ISSUE TITLE
УБРАТЬ ЭТУ ИКОНКУ МЕНЮ! (новый дизайн)

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#5]
Санек, ты и сам предложил убрать эту иконку, я посидел посмотрел ещё новый дизайн и понял что меню в шапочке расположенное по горизонтали достаточно...
Убери пожалуйста эту иконку. На картинке которую прислал, выделил, что нужно убрать.

![whatsapp image 2017-11-01 at 12 59 41](https://user-images.githubusercontent.com/33026187/32269923-f88ba060-bf04-11e7-9597-083efdae9ae9.jpeg)

**Comment by Siyet** [comment]
Иконку убрал
