### ISSUE TITLE
Рекламные слайды (новый дизайн)

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#6]
1) В высоту рекламные слайды нужно сделать меньше.
2) Нажать на слайд и перейти по ссылке (которая наложена на слайд) можно только на определённой зоне... Нужно сделать так, чтобы можно было нажать в любую точку слайда и перейти по ссылке данного слайда. Так же, нужно убрать возможность добавления текста на слайд, так как всё будет указанно на картинке. В итоге в слайд требуется добавлять только картинку и ссылку.

**Comment by Siyet** [comment]
Изменил высоту слайда с 540px до 400px.
Текст и наименование слайда выпилил вообще.
Оставил сроки действия слайда.
