### ISSUE TITLE
Иконки ПОИСКА и КОРЗИНЫ (новый дизайн)

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#7]
1) Иконки ПОИСКА и КОРЗИНЫ по высоте расположены одна выше другой - нужно выровнять.
2) Когда начинаешь колёсиком мышки двигать вверх, вниз, эти иконки двигаются раздельно, тоже нужно подправить.

**Comment by Siyet** [comment]
Иконки выровнял

**Comment by Siyet** [comment]
Теперь иконки двигаются вместе
