### ISSUE TITLE
Корзина (наведи курсор на иконку корзины) (новый дизайн)

### ISSUE THREAD

**Issue by Maksromashkin** [Siyet/dl#8]
Добавь 2-3 товара в корзину и наведи курсор на иконку корзины:
1) Общая сумма показывается под каждым товаром, нужно исправить и сделать один итог после всех товаров. Так же под каждым товаром высвечивается иконка ПЕРЕЙТИ В КОРЗИНУ. Сделать её тоже в конце после итоговой суммы в единичном экземпляре и цвета смотри, там стоят на этой иконке от макромага))
2) Сделать возможность удаления товара из корзины не заходив в неё (т.е., просто наведя курсор на иконку).
3) Название товара, фотографию, цену каждого товара и общую сумму - сделать меньше размером.
4) После итоговой суммы (опять же при наведении курсора на иконку) указать следующую фразу и маленький значок _ВНИМАНИЕ: Общая стоимость товаров в корзине указана без учёта доставки. Стоимость доставки уточняйте у оператора, либо в разделе "Доставка/самовывоз", либо при самостоятельном оформлении заказа итоговая сумма пересчитается автоматически._

**Comment by Siyet** [comment]
Все сделано, кроме пункта 2.

**Comment by Siyet** [comment]
Сделал пункт 2
